# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('medicion', models.TextField()),
                ('rango_esp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rango_mid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rango_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Norma'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proceso'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo'),
        ),
    ]
