# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='codigo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='norma',
            name='entidad',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='norma',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='norma',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
