# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180925_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='indicador',
            name='medicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo'),
        ),
    ]
