# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180925_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Area'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='objetivo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cargo'),
        ),
    ]
